/// Re-exported for use in code generated by `#[roos::tool]`.
#[doc(hidden)]
pub use schemars;

pub mod agent;
pub mod bus;
pub mod config;
pub mod error;
pub mod memory;
pub mod provider;
pub mod tool;
pub mod types;

pub use agent::Agent;
pub use bus::{BusError, BusEvent, BusMessage, RoosAgentBus};
pub use config::{AgentConfig, ConfigError, MemoryConfig, ProviderConfig, RoosConfig};
pub use error::AgentError;
pub use memory::{ConversationHistory, ConversationMessage, Memory, MemoryError};
pub use provider::{
    CompletionConfig, CompletionResponse, LLMProvider, Message, ProviderError, StopReason,
    ToolCall, ToolSchema,
};
pub use tool::{Tool, ToolError};
pub use types::{AgentInput, AgentOutput, TokenUsage, ToolCallRecord};
