use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::quote;
use syn::{
    parse::Parser, parse_macro_input, punctuated::Punctuated, FnArg, Ident, ItemFn, LitStr,
    MetaNameValue, Pat, Token, Type,
};

/// Wraps an `async fn` as a ROOS [`Tool`](roos_core::Tool) implementation.
///
/// # Usage
///
/// ```rust,ignore
/// #[derive(serde::Deserialize, schemars::JsonSchema)]
/// pub struct EchoInput { pub text: String }
///
/// #[roos_macros::tool(name = "echo", description = "Returns input text.")]
/// async fn echo(input: EchoInput) -> Result<String, roos_core::ToolError> {
///     Ok(input.text)
/// }
/// // Generates: `pub struct EchoTool;` implementing `roos_core::Tool`.
/// ```
///
/// # Requirements
/// - The function **must** be `async`.
/// - Exactly **one** typed parameter (the input struct).
/// - The input type must implement `serde::DeserializeOwned` + `schemars::JsonSchema`.
/// - Return type must be `Result<String, roos_core::ToolError>`.
#[proc_macro_attribute]
pub fn tool(args: TokenStream, input: TokenStream) -> TokenStream {
    // ── Parse attribute arguments ────────────────────────────────────────────
    let parser = Punctuated::<MetaNameValue, Token![,]>::parse_terminated;
    let args = match parser.parse(args) {
        Ok(a) => a,
        Err(e) => return e.to_compile_error().into(),
    };

    let mut tool_name: Option<String> = None;
    let mut tool_desc: Option<String> = None;

    for kv in &args {
        let key = kv
            .path
            .get_ident()
            .map(|i| i.to_string())
            .unwrap_or_default();
        match key.as_str() {
            "name" => {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(s),
                    ..
                }) = &kv.value
                {
                    tool_name = Some(s.value());
                }
            }
            "description" => {
                if let syn::Expr::Lit(syn::ExprLit {
                    lit: syn::Lit::Str(s),
                    ..
                }) = &kv.value
                {
                    tool_desc = Some(s.value());
                }
            }
            other => {
                return syn::Error::new_spanned(
                    &kv.path,
                    format!("unknown key `{other}`; expected `name` or `description`"),
                )
                .to_compile_error()
                .into();
            }
        }
    }

    let tool_name = match tool_name {
        Some(n) => n,
        None => {
            return syn::Error::new(Span::call_site(), "`name` is required in #[tool(...)]")
                .to_compile_error()
                .into()
        }
    };
    let tool_desc = match tool_desc {
        Some(d) => d,
        None => {
            return syn::Error::new(
                Span::call_site(),
                "`description` is required in #[tool(...)]",
            )
            .to_compile_error()
            .into()
        }
    };

    // ── Parse the annotated function ─────────────────────────────────────────
    let func = parse_macro_input!(input as ItemFn);
    let func_ident = &func.sig.ident;

    let input_ty: &Type = match func.sig.inputs.first() {
        Some(FnArg::Typed(pat_ty)) => match pat_ty.pat.as_ref() {
            Pat::Ident(_) => &pat_ty.ty,
            _ => {
                return syn::Error::new_spanned(
                    &func.sig.inputs,
                    "#[tool] parameter must be a plain identifier pattern",
                )
                .to_compile_error()
                .into()
            }
        },
        _ => {
            return syn::Error::new_spanned(
                &func.sig.inputs,
                "#[tool] function must have exactly one typed parameter",
            )
            .to_compile_error()
            .into()
        }
    };

    // ── Derive Tool struct name (PascalCase + "Tool") ─────────────────────────
    let struct_name = {
        let raw = func_ident.to_string();
        let pascal: String = raw
            .split('_')
            .filter(|s| !s.is_empty())
            .map(|s| {
                let mut c = s.chars();
                match c.next() {
                    None => String::new(),
                    Some(f) => f.to_uppercase().collect::<String>() + c.as_str(),
                }
            })
            .collect();
        Ident::new(&format!("{pascal}Tool"), func_ident.span())
    };

    let name_lit = LitStr::new(&tool_name, Span::call_site());
    let desc_lit = LitStr::new(&tool_desc, Span::call_site());

    // ── Generate Tool impl using Box::pin (avoids async_trait re-export) ──────
    let expanded = quote! {
        #func

        /// Generated by `#[roos_macros::tool]`.
        pub struct #struct_name;

        impl ::roos_core::Tool for #struct_name {
            fn name(&self) -> &str {
                #name_lit
            }

            fn description(&self) -> &str {
                #desc_lit
            }

            fn schema(&self) -> ::serde_json::Value {
                ::serde_json::to_value(
                    ::roos_core::schemars::schema_for!(#input_ty)
                )
                .unwrap_or_default()
            }

            fn execute<'life0, 'async_trait>(
                &'life0 self,
                input: ::serde_json::Value,
            ) -> ::core::pin::Pin<
                ::std::boxed::Box<
                    dyn ::core::future::Future<
                        Output = ::core::result::Result<
                            ::std::string::String,
                            ::roos_core::ToolError,
                        >,
                    > + ::core::marker::Send + 'async_trait,
                >,
            >
            where
                'life0: 'async_trait,
                Self: 'async_trait,
            {
                ::std::boxed::Box::pin(async move {
                    let typed: #input_ty =
                        ::serde_json::from_value(input).map_err(|e| {
                            ::roos_core::ToolError::InvalidInput {
                                tool: #name_lit.to_owned(),
                                reason: e.to_string(),
                            }
                        })?;
                    #func_ident(typed).await
                })
            }
        }
    };

    expanded.into()
}
